version: '2'
services:
  swift-microservice:
    build: swift-microservice
    command: npm run start-dev
    volumes:
      - ./swift-microservice:/usr/app
      - /usr/app/node_modules
    ports:
      - "3100:8090"
    links:
      - mongo
  node-microservice:
    build: node-microservice
    command: npm run start-dev
    volumes:
      - ./node-microservice:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    links:
      - mongo
  # spring-microservice:
  #   build: spring-microservice
  #   command: java -jar target/gs-spring-boot-0.1.0.jar
  #   volumes:
  #     - ./spring-microservice:/usr/app
  #   ports:
  #     - "8080:8080"
  #   links:
  #     - mongo
  mongo:
    image: mongo:latest
  # redis:
  #   image: redis
  # zipkin:
  #   image: openzipkin/zipkin